In [ ]:
#quickSort

def partition(A,p,r):
    i=p-1
    x=A[r]
    for j in range(p,r):
        if A[j]<=x:
            i=i+1
            tmp=A[i]
            A[i]=A[j]
            A[j]=tmp
    tmp=A[i+1]
    A[i+1]=A[r]
    A[r]=tmp
    return i+1
        
def quicksort(A,p,r):
    if p<r:
        q=partition(A,p,r)
        quicksort(A,p,q-1)
        quicksort(A,q+1,r)

a=[2,8,7,3,5,6,4]
quicksort(a,0,len(a)-1)
print(a)


In [5]:
#mergesort
def mergesort(A):
    if len(A)<=1:
        return A
    mid=len(A)//2
    l=mergesort(A[0:mid])
    r=mergesort(A[mid:])
    return merge(l,r)

def merge(l,r):
    s=[None]*(len(l)+len(r))
    i=0
    j=0
    k=0
    while(i<len(l) and j<len(r)):
        if l[i]<=r[j]:
            s[k]=l[i]
            i+=1
        else:
            s[k]=r[j]
            j+=1
        k+=1
    while(i<len(l)):
        s[k]=l[i]
        i+=1
        k+=1
    while(j<len(r)):
        s[k]=r[j]
        j+=1
        k+=1
    return s

a=[2,8,7,3,5,6,4]
a1=[1,3,7,9]
a2=[2,5,8,20,30]
print(mergesort(a))
#print(merge(a1,a2))

[2, 3, 4, 5, 6, 7, 8]


In [17]:
#bublesort

def bublesort(a):
    for i in range(len(a)):
        for j in range(i+1, len(a)):
            if a[i]> a[j]:
                t=a[i]
                a[i]=a[j]
                a[j]=t
    return a
                
a2=[500,2,100,5,-3,8,20,30]                
print(bublesort(a2))


[-3, 2, 5, 8, 20, 30, 100, 500]


In [ ]:
import numpy as np
n=[2,3,6,7]
result=[[]]
def comb(s):
    global result
    if len(s)==0: return
    result.append(s)
    print(s)
    for i in range(0, len(s)):
        t = s[0:i] + s[i + 1:]
        comb(t)

res = [[]]
comb(n)
result=np.unique(result)
#print(result)
print(len(result))

In [70]:
#Trie Implementation
#print (ord('a'))
#print (chr(97))
class Trie:
    def __init__(self,val=''):
        self.isEnd=0
        self.cnt=0
        self.children={}
        self.val=val
    def add(self,ch,isEnd):
        if ch not in self.children.keys():
            self.children[ch]=Trie(ch)
        self.cnt=self.cnt+1
        self.isEnd=isEnd
        return self.children[ch]

def insert(strs, root):
    isEnd=0
    if len(strs)==1:
        isEnd=1
    chld=root.add(strs[0],isEnd)
    isEnd=0
    for i in range(1,len(strs)):
        if (i==len(strs)-1):
            isEnd=1
        chld=chld.add(strs[i],isEnd)

def traverse(root,path,L):
    if root is None:
        return
    chld=root.children
    path.append(root.val)
    if chld is None or len(chld.keys())==0:
        L.append(path)
        return

    for k in chld.keys():
        #print(k)
        traverse(chld[k],path+[],L)
def search(root,strs):
    for i in range(len(strs)):
        chld=root.children
        if strs[i] not in chld.keys():
            return False
        root=chld[strs[i]]
        print(root.cnt)
    return True, root.cnt
    

p=[]
root=Trie()
insert("bear", root)
insert("bell",root)
insert("sport",root)
insert("stop",root)
L=[]
#traverse(root,[],L)
print(L)
print(search(root,"sp"))

    
        
        




[]
2
1
(True, 1)


In [7]:
from itertools import permutations 
#print(list(permutations("text",2)))
d=set(list(permutations("text",2)))
for p in d:
    print("".join(p))

et
tx
tt
ex
xt
xe
te


Sorting Object Using Priority Queue
========

In [8]:
import queue
class Employee:
    def __init__(self, name=None,salary=0, age=0):
        self.name=name
        self.salary=salary
        self.age=age

emp1=Employee("Shahinur", -120, 35)
emp2=Employee("jeff", -110, 45)
emp3=Employee("khaled", -300, 45)
emp4=Employee("bh", -150, 40)
pq=queue.PriorityQueue()
pq.put((emp1.salary,emp1))
pq.put((emp2.salary,emp2))
pq.put((emp3.salary,emp3))
pq.put((emp4.salary,emp4))

while(pq.empty()==False):
    salary, emp=pq.get()
    print(emp.name,-1*salary)



khaled 300
bh 150
Shahinur 120
jeff 110


In [13]:
a=10
b=12
print (b & a)

8


In [9]:
import numpy as np

import sys

arr=np.random.randint(10)
print(arr)
try:
    for i in range(10):
        tx=10/0
except:
    print (sys.exc_info()[0])
finally:
    print(tx)

9
<class 'ZeroDivisionError'>
5.0


In [34]:
a=[[]]*10

size=5
queue=[]*5

def enqueue(e):
    if len(queue)<size:
        queue.append(e)
    else:
        print("queue is full")
def deq():
    if len(queue)>0:
        return queue.pop(0)
    else:
        print("Queue is empty")
        return None

enqueue(10)
enqueue(11)
enqueue(12)
enqueue(13)
enqueue(14)
enqueue(17)
print(deq())
enqueue(18)
print(deq())


queue is full
10
11


In [42]:
class staticvar:
    val=0
    def __init__(self, name, salary):
        self.name=name
        self.salary=salary
        
staticvar.val=100
o1=staticvar("Sh", 120)
o1.val=500
o2=staticvar("jJ", 130)
o2.val=300
print(o2.val)
        

300


In [96]:
#polymorphism and inheritance
class person:
    def __init__(self, name, salary):
        self.name=name
        self.salary=salary
    def printf(self):
        print("base class",self.name,self.salary)
class student(person):
    def __init__(self, name,salary, cgpa):
        super().__init__( name, salary)
        self.cgpa=cgpa
    def printf(self):
        print("Child..",self.name,self.salary,self.cgpa)

obj=student("name",100,3.4)
obj.printf()

Child.. name 100 3.4


In [44]:
#Singleton

class singleton:
    instance=None
    @staticmethod
    def getinstance():
        if singleton.instance is None:
            singleton.instance=singleton()
        return singleton.instance
    def __init__(self):
        if singleton.instance is not None:
            raise Exception("Dont even think it. Its Singleton")
        else:
             singleton.instance=self
        

o1=singleton()
o2=singleton()

Exception: Dont even think it. Its Singleton

In [55]:
def testgen():
    num=0
    while True:
        yield num
        num=num+1

gen=testgen()
for i,val in enumerate (gen):
    if i >10:
        break
    print(val)


0
1
2
3
4
5
6
7
8
9
10


In [56]:
weekdays = ['sun','mon','tue','wed','thu','fri','sat']
listAsString = ' '.join(weekdays)

print(listAsString)

sun mon tue wed thu fri sat


In [63]:
num=1354
rev=0
while num>0:
    rev=rev*10+num%10
    print(rev)
    num=int(num/10)
print(rev)

4
45
453
4531
4531


In [165]:
import sys
import queue
graph={}
num_vert=8
class node:
    def __init__(self, val=0,dist=sys.maxsize,isvisied=False,parent=None,edge_length=1):
        self.val=val
        self.dist=dist
        self.isvisied=isvisied
        self.parent=parent
        self.neighbor=[]
        self.edge_length=1
def add_edges(source,dest):
    if source in graph.keys():
        sn=graph[source]
    else:
        sn=node(val=source)
        graph[source]=sn
    if dest in graph.keys():
        dt=graph[dest]
    else:
        dt=node(val=dest)
        graph[dest]=dt
    sn.neighbor.append(dt)
    #dt.neighbor.append(sn)
    
add_edges(1,2)
add_edges(1,5)
add_edges(2,6)
add_edges(6,3)
add_edges(6,7)
add_edges(3,4)
add_edges(3,7)
add_edges(7,4)
add_edges(7,8)
add_edges(4,8)
#print(len(graph[7].neighbor))

def BFS(source):
    node=graph[source]
    node.parent=None
    node.dist=0
    node.isvisied=True
    q=[]
    q.append(node)
    while(len(q)>0):
        nd=q.pop(0)
        for child in nd.neighbor:
            if child.isvisied==False:
                q.append(child)
                child.isvisied=True
                child.parent=nd
                child.dist=nd.dist+1

                
def shortest_path(source,dest):
    pq=queue.PriorityQueue()
    sn=graph[source]
    sn.dist=0
    sn.parent=None
    dn=graph[dest]
    S=set()
    for nd in graph.keys():
        pq.put((nd,graph[nd]))
    while(pq.empty()==False):
        dist,node=pq.get()
        S.add(node.val)
        for chld in node.neighbor:
            if chld.dist>node.dist+node.edge_length:
                chld.dist=node.dist+node.edge_length
                chld.parent=node
    
    path=""
    while(dn.parent is not None or dn.parent==sn):
        path= str(dn.val)+"-->"+path
        dn=dn.parent
    print(str(source)+"-->"+path)
    print(S)
    
        
    
#BFS(2)   
def find_path(s, d, L, C) :
    if s.val==d.val or s is None:
        C.append(d.val)
        L.append(C)
        return L
    s.isvisied=True
    C.append(s.val)
    for chld in s.neighbor:
        find_path(chld,d,L,C+[])
    return 

def allpaths(source, dest):
    if source not in graph.keys() or dest not in graph.keys():
        print("no path")
        return
    else:
        sn=graph[source]
        dn=graph[dest]
        L=[]
        find_path(sn,dn,L,[])
        print(L)

allpaths(2,8)  
shortest_path(1,4)
    
    

[[2, 6, 3, 4, 8], [2, 6, 3, 7, 4, 8], [2, 6, 3, 7, 8], [2, 6, 7, 4, 8], [2, 6, 7, 8]]
1-->2-->6-->7-->4-->
{1, 2, 3, 4, 5, 6, 7, 8}


In [172]:
import pickle
import numpy as np
dicts={}
ss=np.random.randint(1,3,(10,10))
tt=np.random.randint(1,3,(10,10))
dicts["salam"]=ss
dicts["john"]=tt

with open("test.pickle","wb") as f:
    pickle.dump(dicts,f)

with open("test.pickle","rb") as f:
    test=pickle.load(f)   
print(test["salam"])

[[2 2 1 2 2 2 1 1 2 1]
 [2 2 2 2 1 1 2 1 1 2]
 [1 2 2 1 2 2 1 1 1 2]
 [2 1 2 2 2 1 1 1 2 1]
 [2 1 1 1 1 1 2 2 1 1]
 [1 2 2 1 1 1 1 1 1 2]
 [2 1 2 2 2 1 1 2 1 2]
 [2 2 2 1 2 1 1 2 1 2]
 [2 2 2 2 2 2 2 2 2 1]
 [1 1 2 1 2 1 1 2 1 2]]


In [179]:
a = np.array([[12, 15], [10, 1],[9, 20]])
arr1 = np.sort(a, axis = 0)
print(arr1[:,0])

[ 9 10 12]


In [189]:
arr=[1,30,4,0,4,0,0,3,0,6]
pos=0
for i in range(len(arr)):
    if arr[i]!=0:
        arr[pos]=arr[i]
        pos+=1

print(arr)

arr=[1,30,4,0,4,0,0,3,0,6]
pos=len(arr)-1
for i in range(len(arr)-1,-1,-1):
    if arr[i]!=0:
        arr[pos]=arr[i]
        pos-=1
while(pos>=0):
    arr[pos]=0
    pos-=1
print(arr)

[1, 30, 4, 4, 3, 6, 0, 3, 0, 6]
[0, 0, 0, 0, 1, 30, 4, 4, 3, 6]


In [197]:
l=[[1, 5],[1,6], [3, 7], [4, 6], [6, 8], [10,15],[12,20]]
i=1

while i<len(l):
    if l[i-1][0]==l[i][0]:
        l[i-1][1]=max(l[i-1][1],l[i][1])
        l.pop(i)
        continue
    if l[i-1][1]>l[i][0] and l[i-1][1]<l[i][1]:
        l[i-1][1]=l[i][1]
        l.pop(i)
        continue
    if l[i-1][1]>l[i][1]:
        l.pop(i)
        continue
    i+=1
print(l)
    


[[1, 8], [10, 20]]
